image: python:3.10

stages:
  - analyze
  - test

# Stage Analyze

analyze:pylint:
  stage: analyze
  script:
    - pip install [.test]
    - pylint ./aiowiserbyfeller
  interruptible: true
  allow_failure: true

analyze:black:
  stage: analyze
  script:
    - pip install [.test]
    - black ./aiowiserbyfeller --check
  interruptible: true

# Stage Test

test:pytest:
  stage: test
  script:
    - pip install [.test]
    - pytest --cov=aiowiserbyfeller --cov-report term --cov-report xml:coverage.xml --junitxml=junit.xml tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    expire_in: 1 w
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
  interruptible: true
